service: puppeteer

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  stage: test



functions:
  screenshot:
    description: handler
    memorySize: 1536
    timeout: 30
    handler: index.handler
    events:
      - http:
          path: "{path+}"
          method: get

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - "*/*"
