service: puppeteer

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  stage: test
  environment:
    DEFAULT_URL: https://example.com/
    DEFAULT_WIDTH: 1200
    DEFAULT_HEIGHT: 630
    USER_AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
    ALLOW_URL_PATTERN: ^https://example\.com/?.*

functions:
  screenshot:
    description: handler
    memorySize: 1536
    timeout: 30
    handler: index.handler
    events:
      - http:
          path: ""
          method: get

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - "*/*"
