service: puppeteer

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  stage: test
  environment:
    DEFAULT_URL: https://example.com/
    DEFAULT_WIDTH: 1200
    DEFAULT_HEIGHT: 630

functions:
  screenshot:
    description: handler
    memorySize: 1536
    timeout: 30
    handler: index.handler
    events:
      - http:
          path: ""
          method: get

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - "*/*"
